import { GoogleGenAI } from '@google/genai';

let _client = null;

function getGeminiClient() {
    if (!_client) {
        _client = new GoogleGenAI({
            apiKey: process.env.GEMINI_API_KEY,
        });
    }
    return _client;
}

/**
 * Generate text using Google Gemini
 */
export async function generateText(messages, options = {}) {
    try {
        if (!process.env.GEMINI_API_KEY) {
            throw new Error('GEMINI_API_KEY not set');
        }

        const client = getGeminiClient();

        // Convert messages format for Gemini
        const content = messages
            .filter(m => m.role === 'user')
            .map(m => m.content)
            .join('\n');

        if (!content) {
            throw new Error('No user message found');
        }

        const response = await client.models.generateContent({
            model: 'gemini-2.0-flash',
            contents: {
                role: 'user',
                parts: [{
                    text: content
                }]
            },
            generationConfig: {
                maxOutputTokens: options.max_tokens || 1000,
                temperature: options.temperature || 0.7,
            }
        });

        // Extract the text from the response
        const text = response.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!text) {
            throw new Error('No text generated by Gemini');
        }

        return text;
    } catch (error) {
        console.error('Gemini text generation error:', error);
        throw new Error(error?.message || 'Failed to generate text with Gemini API');
    }
}

/**
 * Generate a single image using Gemini's Imagen 3.
 */
export async function generateImage(prompt, aspectRatio = '1:1') {
    try {
        const client = getGeminiClient();

        const response = await client.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: `A beautiful, artistic illustration for a storybook: ${prompt}. Style: digital art, vivid colors, high quality, suitable for a story illustration.`,
            config: {
                numberOfImages: 1,
                aspectRatio: aspectRatio,
                outputMimeType: 'image/png',
            }
        });

        // The image is returned as base64 in the response
        if (!response?.generatedImages?.[0]?.image?.imageBytes) {
            throw new Error('No image generated by Gemini');
        }

        const base64Data = response.generatedImages[0].image.imageBytes;
        const url = `data:image/png;base64,${base64Data}`;

        return {
            url: url,
            revisedPrompt: prompt, // Gemini doesn't return a revised prompt
        };
    } catch (error) {
        console.error('Gemini image generation error:', error);
        
        let errorMessage = 'Failed to generate image with Gemini API';
        if (error.status === 400 || error.message?.includes('400')) {
            errorMessage = 'Invalid request to Gemini (400). Please check your prompt or API restrictions.';
        } else if (error.status === 403 || error.message?.includes('403')) {
            errorMessage = 'API Key is invalid or has no access to Imagen (403).';
        }
        throw new Error(error?.message || errorMessage);
    }
}

/**
 * Generate multiple images using Gemini's Imagen 3.
 */
export async function generateMultipleImages(prompt, count = 3) {
    try {
        const client = getGeminiClient();

        // Gemini only supports generating 1-4 images at a time (some limits apply to 4 depending on ratio)
        // For standard 1:1, up to 4 is supported.
        const numImages = Math.min(count, 4);

        const response = await client.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: `A beautiful, artistic illustration for a storybook: ${prompt}. Style: digital art, vivid colors, high quality.`,
            config: {
                numberOfImages: numImages,
                aspectRatio: '1:1',
                outputMimeType: 'image/png',
            }
        });

        if (!response?.generatedImages || response.generatedImages.length === 0) {
            throw new Error('No images generated by Gemini');
        }

        const results = response.generatedImages.map(img => {
            const base64Data = img.image.imageBytes;
            return {
                url: `data:image/png;base64,${base64Data}`,
                revisedPrompt: prompt,
            };
        });
        
        return results;

    } catch (error) {
        console.error('Multiple image generation error (Gemini):', error);
        throw new Error(error?.message || 'Failed to generate images with Gemini API');
    }
}
