/**
 * Generate text using OpenRouter
 */
export async function generateText(messages, options = {}) {
    const apiKey = process.env.OPENROUTER_API_KEY;
    
    if (!apiKey) {
        throw new Error('OpenRouter API key is missing.');
    }

    try {
        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${apiKey}`,
                "Content-Type": "application/json",
                "HTTP-Referer": process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
                "X-Title": "StoryForge",
            },
            body: JSON.stringify({
                model: "meta-llama/llama-3-8b-instruct",
                messages: messages,
                max_tokens: options.max_tokens || 1000,
                temperature: options.temperature || 0.7,
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`OpenRouter API Error (${response.status}): ${errorText}`);
        }

        const data = await response.json();
        const content = data.choices?.[0]?.message?.content;

        if (!content) {
            throw new Error('No text generated by OpenRouter');
        }

        return content;
    } catch (error) {
        console.error('OpenRouter text generation error:', error);
        throw new Error(error.message || 'Failed to generate text with OpenRouter');
    }
}

export async function generateImage(prompt, aspectRatio = '1:1') {
    const apiKey = process.env.OPENROUTER_API_KEY;
    
    if (!apiKey) {
        throw new Error('OpenRouter API key is missing. Please add OPENROUTER_API_KEY to your .env.local file.');
    }

    try {
        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${apiKey}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                model: "sourceful/riverflow-v2-pro",
                messages: [
                    { 
                        role: "user", 
                        content: `A beautiful, artistic illustration for a storybook: ${prompt}. Style: digital art, vivid colors, high quality, suitable for a story illustration.` 
                    }
                ],
                // OpenRouter specific parameters to generate an image rather than text
                modalities: ["image"], 
                // Sourceful supports specific image_configs
                // See: https://openrouter.ai/docs/features/multimodal/image-generation
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`OpenRouter API Error (${response.status}): ${errorText}`);
        }

        const data = await response.json();
        const messageText = data.choices?.[0]?.message?.content || "";
        
        // OpenRouter returns the image URL either in Markdown format ![image](url) or just the raw URL.
        // We need to parse it out.
        let imageUrl = messageText;
        const markdownRegex = /!\[.*?\]\((.*?)\)/;
        const match = messageText.match(markdownRegex);
        
        if (match && match[1]) {
            imageUrl = match[1];
        } else if (messageText.includes('http')) {
             // Fallback: extract the first URL if it's not proper markdown
             const urlRegex = /(https?:\/\/[^\s]+)/;
             const urlMatch = messageText.match(urlRegex);
             if (urlMatch) imageUrl = urlMatch[1];
        } else {
             console.error("Unexpected OpenRouter response:", data);
             throw new Error('Could not parse image URL from OpenRouter response');
        }

        return {
            url: imageUrl,
            revisedPrompt: prompt
        };
    } catch (error) {
        console.error('OpenRouter image generation error:', error);
        throw new Error(error.message || 'Failed to generate image with OpenRouter');
    }
}

export async function generateMultipleImages(prompt, count = 3) {
    try {
        const promises = Array.from({ length: Math.min(count, 4) }, () => generateImage(prompt));
        const results = await Promise.allSettled(promises);
        
        const successfulImages = results
            .filter(r => r.status === 'fulfilled')
            .map(r => ({ url: r.value.url, revisedPrompt: prompt }));
            
        if (successfulImages.length === 0) {
            throw new Error('All image generation requests failed.');
        }
        
        return successfulImages;
    } catch (error) {
        console.error('Multiple image generation error (OpenRouter):', error);
        throw new Error(error.message || 'Failed to generate images with OpenRouter');
    }
}
